'use strict';

const { generateDashboard } = require('../lib/dashboard');
const { JSDOM } = require('jsdom');

describe('Dashboard HTML contract', () => {
  let doc;

  beforeAll(() => {
    const html = generateDashboard({ nonce: '', cspEnabled: false });
    doc = new JSDOM(html).window.document;
  });

  test('health ribbon exists', () => {
    const ribbon = doc.querySelector('[data-testid="health-ribbon"]');
    expect(ribbon).not.toBeNull();
  });

  test('heatmap container exists', () => {
    const heatmap = doc.getElementById('keysHeatmap');
    expect(heatmap).not.toBeNull();
  });

  test('persistent header z.ai usage pill exists', () => {
    const usagePill = doc.querySelector('[data-testid="header-account-usage"]');
    const tokenLabel = doc.getElementById('headerAccountTokenPct');
    const toolLabel = doc.getElementById('headerAccountToolPct');
    expect(usagePill).not.toBeNull();
    expect(tokenLabel).not.toBeNull();
    expect(toolLabel).not.toBeNull();
  });

  test('chart canvases exist', () => {
    const requestChart = doc.getElementById('requestChart');
    const latencyChart = doc.getElementById('latencyChart');
    const errorChart = doc.getElementById('errorChart');
    const distChart = doc.getElementById('distChart');

    expect(requestChart).not.toBeNull();
    expect(latencyChart).not.toBeNull();
    expect(errorChart).not.toBeNull();
    expect(distChart).not.toBeNull();
  });

  test('dock tabs exist', () => {
    const tabIds = ['tab-live', 'tab-traces', 'tab-logs', 'tab-queue', 'tab-circuit'];

    for (const id of tabIds) {
      const tab = doc.querySelector(`[data-testid="${id}"]`);
      expect(tab).not.toBeNull();
    }
  });

  test('trace table has body', () => {
    const tracesBody = doc.getElementById('tracesBody');
    expect(tracesBody).not.toBeNull();
    expect(tracesBody.tagName).toBe('TBODY');
    expect(tracesBody.closest('table')).not.toBeNull();
  });

  test('cost panel exists', () => {
    const costPanel = doc.getElementById('costPanel');
    expect(costPanel).not.toBeNull();
  });

  test('external CSS and JS links', () => {
    // Phase 5: CSS split into modular files — check for any CSS link
    const cssLinks = doc.querySelectorAll('link[rel="stylesheet"]');
    // Phase 6: JS split into modular files under /dashboard/js/
    const jsScripts = doc.querySelectorAll('script[src*="/dashboard/js/"]');

    expect(cssLinks.length).toBeGreaterThan(0);
    expect(jsScripts.length).toBe(15);
  });

  test('keyboard shortcuts modal', () => {
    const modal = doc.getElementById('shortcutsModal');
    expect(modal).not.toBeNull();

    const items = modal.querySelectorAll('.shortcut-item');
    expect(items.length).toBeGreaterThan(0);
  });

  test('no inline style blocks in body', () => {
    const inlineStyles = doc.querySelectorAll('body style');
    expect(inlineStyles.length).toBe(0);
  });

  test('modular JS scripts exist confirming JS is externalized', () => {
    // Phase 6: JS split into 10 modular files loaded in dependency order
    const storeScript = doc.querySelector('script[src*="js/store.js"]');
    const initScript = doc.querySelector('script[src*="js/init.js"]');
    expect(storeScript).not.toBeNull();
    expect(initScript).not.toBeNull();
  });

  test('no element should have duplicate class attributes', () => {
    const html = generateDashboard({ nonce: '', cspEnabled: false });
    // Match patterns like: class="..." class="..."
    const duplicateClasses = html.match(/class="[^"]*"\s+class="/g);
    expect(duplicateClasses || []).toHaveLength(0);
  });

  test('elements with id and class should have single merged class attribute', () => {
    const html = generateDashboard({ nonce: '', cspEnabled: false });
    // Check for patterns like: id="..." class="..." class="..." (duplicate class after id)
    const duplicateClassAfterId = html.match(/id="[^"]*"[^>]*class="[^"]*"\s+class="/g);
    expect(duplicateClassAfterId || []).toHaveLength(0);
  });

  test('global search input aria-controls points to searchHistoryDropdown', () => {
    const searchInput = doc.getElementById('globalSearchInput');
    expect(searchInput).not.toBeNull();
    expect(searchInput.getAttribute('aria-controls')).toBe('searchHistoryDropdown');
  });

  test('searchHistoryDropdown element exists', () => {
    const dropdown = doc.getElementById('searchHistoryDropdown');
    expect(dropdown).not.toBeNull();
  });
});

describe('HTML Structure Contracts', () => {
    // These tests use the dashboard HTML generated by the server
    const { generateDashboard: generateDashboardHtml } = require('../lib/dashboard');

    let html;
    beforeAll(() => {
        // Generate dashboard HTML with mock nonce
        html = typeof generateDashboardHtml === 'function'
            ? generateDashboardHtml({ nonce: 'test-nonce-123' })
            : '';
    });

    test('no emoji characters in HTML structure', () => {
        if (!html) return;
        // Check for common emoji ranges (excluding CSS/JS content where they might be in strings)
        // Only check the HTML tag structure, not script/style content
        const htmlOnly = html.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<style[\s\S]*?<\/style>/g, '');
        const emojiPattern = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/u;
        // This will initially fail - that's fine, it becomes the ratchet
        // For now, just count them
        const matches = htmlOnly.match(new RegExp(emojiPattern.source, 'gu'));
        // Record the count as a ratchet metric
        const emojiCount = matches ? matches.length : 0;
        // Initially allow up to 50 (will ratchet down as we replace with SVGs)
        expect(emojiCount).toBeLessThanOrEqual(50);
    });

    test('interactive elements have data-action or aria-label', () => {
        if (!html) return;
        // Count buttons without data-action or aria-label
        const buttonPattern = /<button[^>]*>/g;
        const buttons = html.match(buttonPattern) || [];
        let missingCount = 0;
        for (const btn of buttons) {
            if (!btn.includes('data-action') && !btn.includes('aria-label') && !btn.includes('aria-labelledby')) {
                missingCount++;
            }
        }
        // Allow up to 20 without (will ratchet down)
        expect(missingCount).toBeLessThanOrEqual(20);
    });
});
